require("config.keymaps.basic")
require("config.keymaps.recurva")
require("config.keymaps.quick-edit")
require("config.keymaps.macos")
require("config.keymaps.leader")
require("config.keymaps.custom")
require("config.keymaps.views")
require("config.keymaps.shortcuts")
